title: Free Software Magazine
description: Free Software Magazine is a mostly free-content online magazine about free software.
baseurl: ""
url: "https://www.freesoftwaremagazine.com"

markdown: kramdown
permalink: pretty
highlighter: none

kramdown:
  auto_ids: false
  syntax_highlighter: null
  syntax_highlighter_opts:
    disable: true
  smart_quotes: ["apos", "apos", "quot", "quot"]

exclude:
  - node_modules
  - vendor
  - legacy

include:
  - tags/.net

defaults:
  - scope:
      path: "articles"
      type: pages
    values:
      layout: article
      render_with_liquid: false
      listed: "true"
      license: verbatim_only
      section: opinions
  - scope:
      path: "pages"
      type: pages
    values:
      layout: generic
      render_with_liquid: false
